### ISSUE TITLE
Wrong Pinvoke signature (results in crash in case of solver warnings)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.SimModel#120]
If there are solver warnings: error message below comes
![grafik](https://user-images.githubusercontent.com/25061876/107639520-42a2c580-6c71-11eb-86fc-cba9d992e65d.png)

The reason is: PInvoke signature of `FillSolverWarnings` does not match the exported function:
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/08fb0d56cc0ca017f0491ff615267ace2f69d07a/src/OSPSuite.SimModel/Simulation.cs#L177-L179

https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/08fb0d56cc0ca017f0491ff615267ace2f69d07a/src/OSPSuite.SimModelNative/include/SimModel/PInvokeSimulation.h#L135

**Comment by Yuri05** [comment]
@AndreDlm FYI

**Comment by PavelBal** [comment]
I guess it relates to https://github.com/Open-Systems-Pharmacology/MoBi/issues/506 (or vice versa).

**Comment by Yuri05** [comment]
Yes, this must be the reason.
