### ISSUE TITLE
SaveSimulationToXML destroys unicode characters.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.SimModel#28]
See https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/54

**Comment by Yuri05** [comment]
duplicate

**Comment by PavelBal** [comment]
How is this a duplicate? The referenced issue describes the behavior of the R-Toolbox. The problem itself is in SimModelComp_XMLHelper.

**Comment by msevestre** [comment]
Agreed with Pavel. Also this is the issue referenced in PR so let's keep it open
