### ISSUE TITLE
packages.config references nuget packages that are not on nuget

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.SimModel#30]
see [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/master/packages.config)

I

**Comment by msevestre** [comment]
@Yuri05 when you update simmodel for #48, please make sure that no outdated packages is being referenced in SimModel (this might be the case already but better be sure)

**Comment by Yuri05** [comment]
build failed

**Comment by msevestre** [comment]
Did you cancel the build or what?

**Comment by msevestre** [comment]
F##!! C++
