### ISSUE TITLE
Constant variables (with RHS = 0) are not scaled properly

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.SimModel#35]
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/tests/OSPSuite.SimModel.Tests/src/SimulationSpecs.cpp#L2357-L2417

The returned values are 15 and 24, but should be 3 and 4. I.e., start values of constant variables are multiplicated by the scale factors.

**Comment by Yuri05** [comment]
>The returned values are 15 and 24, but should be 3 and 4. I.e., start values of constant variables are multiplicated by the scale factors.

How do you come to this conclusion?
If you enable the test you will see that returned values are 3 and 4 as expected. 

The only problem is (and **that is** why the test is set to `[Ignore]` at the moment): Scaling factors are not properly written back into the XML. But if you keep the lines below commented out and enable the test, it will pass.

https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/master/tests/OSPSuite.SimModel.Tests/src/SimulationSpecs.cpp#L2419-L2421

**Comment by PavelBal** [comment]
> How do you come to this conclusion?
> If you enable the test you will see that returned values are 3 and 4 as expected.

The returned values are as expected because the scaling factors are not saved in the XML, and the simulation is initializied from the XML (i.e., scaling factors are back at 1 at this point). When writing back to the XML is fixed (see https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/pull/36), initial values of constant variables are multiplied with the scaling factors:

https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModel/src/Species.cpp#L249-L261

But, according to specifications, `Species::GetInitialValue` ignores (or should do, which it does not always do) scaling factors.

**Comment by Yuri05** [comment]
Ok, can reproduce, thx for clarification

**Comment by PavelBal** [comment]
This (and the whole scale factors thing)  can be fixed as soon as #44 is done.

**Comment by PavelBal** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/pull/78
