### ISSUE TITLE
Export model as C++ code

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.SimModel#38]
Export models in form of C++ code.
Later on those models can be compiled and used in compiled form e.g. from Matlab/R which will improve computational performance.

**Comment by msevestre** [comment]
@Yuri05 This is not finished correct?

**Comment by Yuri05** [comment]
> This is not finished correct?
Why not?

**Comment by msevestre** [comment]
Well you said this needed to be merged even though this was not finished so that you could move forward. Coding standards are not respected and there are absolutely no tests whatsoever. I see it as WIP but close it if you feel otherwise

**Comment by Yuri05** [comment]
let's make separate issues for that

**Comment by msevestre** [comment]
Separate issue created. Let's try to avoid this situation in the future. Separate branches can coexist without problems and eventually all come into the main branch. This is a typical scenario for a branch "C++ export" where all the code is implemented and then merged into develop branch
