### ISSUE TITLE
TableFormulaWithXArgument should allow time dependent X values

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.SimModel#46]
Currently the problem would be only if X argument depends on one of the ODE variables.
Situations where it depends on Time only (e.g. `X(t)=X0+exp(-Time)`) should be accepted

**Comment by msevestre** [comment]
So currently the problem is ALSO with time dependent variable? 
And do you mean `X(t)=X0+exp(-t))`?

**Comment by Yuri05** [comment]
Yes. Meal-Events make pH in stomach a time dependent function, so currently it does not work with ph-Solubility-table
