### ISSUE TITLE
Feature request: forward "Negative Values Allowed" - information to DCI.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.SimModel#55]
Information about the "Negative Values Allowed" - flag is important for creating excel-sheet with Molecule Start Values for loading in MoBi (e.g., to create steady-state MSV).

This information could  be stored as a property of the species (similarly to "isFormula"-flag).

**Comment by Yuri05** [comment]
obsolete
